import { ColDef } from "ag-grid-community";
import { RbData, WrData } from "@/types/data";

export const colDefsRb: ColDef<RbData>[] = [
  { field: "player", enableRowGroup: true, enablePivot: true},
  { field: "year", enablePivot: true, enableRowGroup: true, filter: "agSetColumnFilter"},
  { field: "position", filter: "agSetColumnFilter" },
  { field: "team_name" },
  { field: "player_game_count", enableValue: true },
  { field: "attempts", enableValue: true },
  { field: "avoided_tackles", enableValue: true },
  { field: "breakaway_attempts", enableValue: true },
  { field: "breakaway_percent", enableValue: true, aggFunc: "avg" },
  { field: "breakaway_yards", enableValue: true },
  { field: "designed_yards", enableValue: true },
  { field: "drops", enableValue: true },
  { field: "elu_recv_mtf", enableValue: true },
  { field: "elu_rush_mtf", enableValue: true },
  { field: "elu_yco", enableValue: true },
  { field: "elusive_rating", enableValue: true },
  { field: "explosive", enableValue: true },
  { field: "first_downs", enableValue: true },
  { field: "fumbles", enableValue: true },
  { field: "grades_offense", enableValue: true },
  { field: "grades_pass", enableValue: true },
  { field: "grades_pass_route", enableValue: true },
  { field: "grades_run", enableValue: true },
  { field: "longest", enableValue: true },
  { field: "rec_yards", enableValue: true },
  { field: "receptions", enableValue: true },
  { field: "routes", enableValue: true },
  { field: "run_plays", enableValue: true },
  { field: "scramble_yards", enableValue: true },
  { field: "scrambles", enableValue: true },
  { field: "targets", enableValue: true },
  { field: "total_touches", enableValue: true },
  { field: "touchdowns", enableValue: true },
  { field: "yards", enableValue: true },
  { field: "yards_after_contact", enableValue: true },
  { field: "yco_attempt", enableValue: true },
  { field: "ypa", enableValue: true },
  { field: "yprr", enableValue: true },
  { field: "zone_attempts", enableValue: true },
];

export const colDefsWr: ColDef<WrData>[] = [
  { field: "player" },
  { field: "player_id" },
  { field: "position" },
  { field: "team_name" },
  { field: "player_game_count" },
  { field: "avg_depth_of_target" },
  { field: "avoided_tackles" },
  { field: "caught_percent" },
  { field: "contested_catch_rate" },
  { field: "contested_receptions" },
  { field: "contested_targets" },
  { field: "declined_penalties" },
  { field: "drop_rate" },
  { field: "drops" },
  { field: "first_downs" },
  { field: "franchise_id" },
  { field: "fumbles" },
  { field: "grades_hands_drop" },
  { field: "grades_hands_fumble" },
  { field: "grades_offense" },
  { field: "grades_pass_block" },
  { field: "grades_pass_route" },
  { field: "inline_rate" },
  { field: "inline_snaps" },
  { field: "interceptions" },
  { field: "longest" },
  { field: "pass_block_rate" },
  { field: "pass_blocks" },
  { field: "pass_plays" },
  { field: "penalties" },
  { field: "receptions" },
  { field: "route_rate" },
  { field: "routes" },
  { field: "slot_rate" },
  { field: "slot_snaps" },
  { field: "targeted_qb_rating" },
  { field: "targets" },
  { field: "touchdowns" },
  { field: "wide_rate" },
  { field: "wide_snaps" },
  { field: "yards" },
  { field: "yards_after_catch" },
  { field: "yards_after_catch_per_reception" },
  { field: "yards_per_reception" },
  { field: "yprr" },
];
